#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := epd_spi
# IDF_PATH := /home/lewin/esp/esp-idf
# IDF_PYTHON_ENV_PATH := /home/lewin/.espressif/python_env/idf4.3_py3.8_env

include ../../component_conf.mk
include $(IDF_PATH)/make/project.mk
