name: Arduino_CI

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "examples/**"
      - "src/**"
      - ".github/workflows/arduino_ci.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        examples:
        - examples/button/button.ino
        - examples/demo/demo.ino
        - examples/drawExample/drawExample.ino
        - examples/drawImages/drawImages.ino
        - examples/grayscale_test/grayscale_test.ino
        - examples/screen_repair/screen_repair.ino
        - examples/spi_driver/spi_driver.ino
        - examples/touch/touch.ino
        - examples/wifi_sync/wifi_sync.ino

    env:
      EXAMPLES: ${{matrix.examples}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Arduino Ci
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz -O arduino-cli.tar.gz ;
          sudo tar xf arduino-cli.tar.gz -C /usr/local/bin arduino-cli ;
          arduino-cli config init ;
          arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json ;
          arduino-cli core update-index ;
          arduino-cli core install esp32:esp32@2.0.14 ;

          arduino-cli lib install "SensorLib"
          arduino-cli lib install "Button2"

      - name: Build examples
        run: |
          cd $GITHUB_WORKSPACE ;
          arduino-cli compile -besp32:esp32:esp32s3:CDCOnBoot=cdc,FlashSize=16M,PartitionScheme=app3M_fat9M_16MB,PSRAM=opi --library . $PWD/$EXAMPLES ;
